NUMPY VS LISTS

In [5]:
python_list = [1,2,3,4,5,6,7,8,9] 

print((python_list) * 2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [1]:
import numpy as np

In [3]:
numpy_array = np.array([1,2,3,4,5,6,7,8,9])

numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
numpy_array = np.array([1,2,3,4,5,6,7,8,9])

print(numpy_array * 2)

[ 2  4  6  8 10 12 14 16 18]


In [6]:
# addition
print(python_list + python_list)

print(numpy_array + numpy_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 2  4  6  8 10 12 14 16 18]


In [16]:
### Returns the dimensions of the array in the format (rows,columns)
## multi - dimensional array

matrix = np.array([[1,2,3,4], [5,6,7,8]])
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

FINDING THE SIZE OF AN ARRAY

In [12]:
## FINDING THE SIZE OF AN ARRAY
##returns how many values are in an array

numpy_array = np.array([1,2,3,4,5,6,7,8,9])
print(numpy_array.size)
        

9


FINDING THE SHAPE OF AN ARRAY

In [17]:
matrix = np.array([[1,2,3,4,] ,  [5,6,7,8,]])
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

SHAPE OF AN ARRAY

In [15]:
print(matrix.shape)

(2, 4)


RESHAPING AN ARRAY

In [18]:
# RESHAPING AN ARRAY
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
matrix.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

EXTRACTING A SPECIFIC VALUE FROM AN ARRAY

In [20]:
array1 = np.array([1,2,3,4,5,6,7,8,9])

array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#array1[6]
array1[-7]

3

In [27]:
array2 = np.array([[2,4,7,9], [6,8,9,4] , [4,7,1,3]])

array2

array([[2, 4, 7, 9],
       [6, 8, 9, 4],
       [4, 7, 1, 3]])

In [29]:
array2[0] [-1]


9

In [30]:
array2 [1] [3]


4

EXTRACTING MULTIPLE VALUES OF AN ARRAY

In [31]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# gets range of values within an array
array1[2:7]


array([3, 4, 5, 6, 7])

In [36]:
array2

array([[2, 4, 7, 9],
       [6, 8, 9, 4],
       [4, 7, 1, 3]])

In [37]:
array2[1]


array([6, 8, 9, 4])

In [38]:
# for specific columns
array2[:,3]

array([9, 4, 3])

REVERSING THE ORDER OF AN ARRAY

In [39]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# output for all values in an array
array1[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
array1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

FINDING THE MAX,MIN AND SUM OF AN ARRAY

In [42]:
array2

array([[2, 4, 7, 9],
       [6, 8, 9, 4],
       [4, 7, 1, 3]])

In [43]:
# Max
print(array2.max())

9


In [44]:
# Min
print(array2.min())

1


In [46]:
# Sum
print(array2.sum())

64


FINDING THE MEAN,MEDIAN, VARIANCE AND STANDARD DEVIATION

In [47]:
array2

array([[2, 4, 7, 9],
       [6, 8, 9, 4],
       [4, 7, 1, 3]])

In [48]:
# mean
print(array2.mean())

5.333333333333333


In [50]:
# median
median = np.median(array2)

median

5.0

In [51]:
# standard deviation
std = np.std(array2)

std

2.592724864350674

In [52]:
# variance
var = np.var(array2)
var

6.722222222222221

In [42]:
n = np.array([[ nan, 0.30163819, nan],
            [0.54629113, 0.67017515, 0.9620984],
            [0.71410713, nan, 0.56288168],  
            [nan,0.60435705,0.83555395]])
n

array([[0.        , 0.30163819, 0.        ],
       [0.54629113, 0.67017515, 0.9620984 ],
       [0.71410713, 0.        , 0.56288168],
       [0.        , 0.60435705, 0.83555395]])

In [43]:
num_one = ([[ nan, 0.30163819, nan],
            [0.54629113, 0.67017515, 0.9620984],
            [0.71410713, nan, 0.56288168],  
            [nan,0.60435705,0.83555395]])
num_one

[[0, 0.30163819, 0],
 [0.54629113, 0.67017515, 0.9620984],
 [0.71410713, 0, 0.56288168],
 [0, 0.60435705, 0.83555395]]